/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as TimelineRouteImport } from './routes/timeline'
import { Route as TrackAlbumRouteImport } from './routes/track/album'
import { Route as TrackBilirubinRouteImport } from './routes/track/bilirubin'
import { Route as TrackDoctorRouteImport } from './routes/track/doctor'
import { Route as TrackMedicinesRouteImport } from './routes/track/medicines'
import { Route as TrackMilestonesRouteImport } from './routes/track/milestones'
import { Route as TrackMilkRouteImport } from './routes/track/milk'
import { Route as TrackPottyRouteImport } from './routes/track/potty'
import { Route as TrackSleepRouteImport } from './routes/track/sleep'
import { Route as TrackVaccinesRouteImport } from './routes/track/vaccines'
import { Route as TrackWeightRouteImport } from './routes/track/weight'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const TimelineRoute = TimelineRouteImport.update({
  id: '/timeline',
  path: '/timeline',
  getParentRoute: () => rootRouteImport,
} as any)
const TrackAlbumRoute = TrackAlbumRouteImport.update({
  id: '/track/album',
  path: '/track/album',
  getParentRoute: () => rootRouteImport,
} as any)
const TrackBilirubinRoute = TrackBilirubinRouteImport.update({
  id: '/track/bilirubin',
  path: '/track/bilirubin',
  getParentRoute: () => rootRouteImport,
} as any)
const TrackDoctorRoute = TrackDoctorRouteImport.update({
  id: '/track/doctor',
  path: '/track/doctor',
  getParentRoute: () => rootRouteImport,
} as any)
const TrackMedicinesRoute = TrackMedicinesRouteImport.update({
  id: '/track/medicines',
  path: '/track/medicines',
  getParentRoute: () => rootRouteImport,
} as any)
const TrackMilestonesRoute = TrackMilestonesRouteImport.update({
  id: '/track/milestones',
  path: '/track/milestones',
  getParentRoute: () => rootRouteImport,
} as any)
const TrackMilkRoute = TrackMilkRouteImport.update({
  id: '/track/milk',
  path: '/track/milk',
  getParentRoute: () => rootRouteImport,
} as any)
const TrackPottyRoute = TrackPottyRouteImport.update({
  id: '/track/potty',
  path: '/track/potty',
  getParentRoute: () => rootRouteImport,
} as any)
const TrackSleepRoute = TrackSleepRouteImport.update({
  id: '/track/sleep',
  path: '/track/sleep',
  getParentRoute: () => rootRouteImport,
} as any)
const TrackVaccinesRoute = TrackVaccinesRouteImport.update({
  id: '/track/vaccines',
  path: '/track/vaccines',
  getParentRoute: () => rootRouteImport,
} as any)
const TrackWeightRoute = TrackWeightRouteImport.update({
  id: '/track/weight',
  path: '/track/weight',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/profile': typeof ProfileRoute
  '/reports': typeof ReportsRoute
  '/settings': typeof SettingsRoute
  '/timeline': typeof TimelineRoute
  '/track/album': typeof TrackAlbumRoute
  '/track/bilirubin': typeof TrackBilirubinRoute
  '/track/doctor': typeof TrackDoctorRoute
  '/track/medicines': typeof TrackMedicinesRoute
  '/track/milestones': typeof TrackMilestonesRoute
  '/track/milk': typeof TrackMilkRoute
  '/track/potty': typeof TrackPottyRoute
  '/track/sleep': typeof TrackSleepRoute
  '/track/vaccines': typeof TrackVaccinesRoute
  '/track/weight': typeof TrackWeightRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/profile': typeof ProfileRoute
  '/reports': typeof ReportsRoute
  '/settings': typeof SettingsRoute
  '/timeline': typeof TimelineRoute
  '/track/album': typeof TrackAlbumRoute
  '/track/bilirubin': typeof TrackBilirubinRoute
  '/track/doctor': typeof TrackDoctorRoute
  '/track/medicines': typeof TrackMedicinesRoute
  '/track/milestones': typeof TrackMilestonesRoute
  '/track/milk': typeof TrackMilkRoute
  '/track/potty': typeof TrackPottyRoute
  '/track/sleep': typeof TrackSleepRoute
  '/track/vaccines': typeof TrackVaccinesRoute
  '/track/weight': typeof TrackWeightRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/profile': typeof ProfileRoute
  '/reports': typeof ReportsRoute
  '/settings': typeof SettingsRoute
  '/timeline': typeof TimelineRoute
  '/track/album': typeof TrackAlbumRoute
  '/track/bilirubin': typeof TrackBilirubinRoute
  '/track/doctor': typeof TrackDoctorRoute
  '/track/medicines': typeof TrackMedicinesRoute
  '/track/milestones': typeof TrackMilestonesRoute
  '/track/milk': typeof TrackMilkRoute
  '/track/potty': typeof TrackPottyRoute
  '/track/sleep': typeof TrackSleepRoute
  '/track/vaccines': typeof TrackVaccinesRoute
  '/track/weight': typeof TrackWeightRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/profile'
    | '/reports'
    | '/settings'
    | '/timeline'
    | '/track/album'
    | '/track/bilirubin'
    | '/track/doctor'
    | '/track/medicines'
    | '/track/milestones'
    | '/track/milk'
    | '/track/potty'
    | '/track/sleep'
    | '/track/vaccines'
    | '/track/weight'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/profile'
    | '/reports'
    | '/settings'
    | '/timeline'
    | '/track/album'
    | '/track/bilirubin'
    | '/track/doctor'
    | '/track/medicines'
    | '/track/milestones'
    | '/track/milk'
    | '/track/potty'
    | '/track/sleep'
    | '/track/vaccines'
    | '/track/weight'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/profile'
    | '/reports'
    | '/settings'
    | '/timeline'
    | '/track/album'
    | '/track/bilirubin'
    | '/track/doctor'
    | '/track/medicines'
    | '/track/milestones'
    | '/track/milk'
    | '/track/potty'
    | '/track/sleep'
    | '/track/vaccines'
    | '/track/weight'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  ProfileRoute: typeof ProfileRoute
  ReportsRoute: typeof ReportsRoute
  SettingsRoute: typeof SettingsRoute
  TimelineRoute: typeof TimelineRoute
  TrackAlbumRoute: typeof TrackAlbumRoute
  TrackBilirubinRoute: typeof TrackBilirubinRoute
  TrackDoctorRoute: typeof TrackDoctorRoute
  TrackMedicinesRoute: typeof TrackMedicinesRoute
  TrackMilestonesRoute: typeof TrackMilestonesRoute
  TrackMilkRoute: typeof TrackMilkRoute
  TrackPottyRoute: typeof TrackPottyRoute
  TrackSleepRoute: typeof TrackSleepRoute
  TrackVaccinesRoute: typeof TrackVaccinesRoute
  TrackWeightRoute: typeof TrackWeightRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/timeline': {
      id: '/timeline'
      path: '/timeline'
      fullPath: '/timeline'
      preLoaderRoute: typeof TimelineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/track/album': {
      id: '/track/album'
      path: '/track/album'
      fullPath: '/track/album'
      preLoaderRoute: typeof TrackAlbumRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/track/bilirubin': {
      id: '/track/bilirubin'
      path: '/track/bilirubin'
      fullPath: '/track/bilirubin'
      preLoaderRoute: typeof TrackBilirubinRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/track/doctor': {
      id: '/track/doctor'
      path: '/track/doctor'
      fullPath: '/track/doctor'
      preLoaderRoute: typeof TrackDoctorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/track/medicines': {
      id: '/track/medicines'
      path: '/track/medicines'
      fullPath: '/track/medicines'
      preLoaderRoute: typeof TrackMedicinesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/track/milestones': {
      id: '/track/milestones'
      path: '/track/milestones'
      fullPath: '/track/milestones'
      preLoaderRoute: typeof TrackMilestonesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/track/milk': {
      id: '/track/milk'
      path: '/track/milk'
      fullPath: '/track/milk'
      preLoaderRoute: typeof TrackMilkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/track/potty': {
      id: '/track/potty'
      path: '/track/potty'
      fullPath: '/track/potty'
      preLoaderRoute: typeof TrackPottyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/track/sleep': {
      id: '/track/sleep'
      path: '/track/sleep'
      fullPath: '/track/sleep'
      preLoaderRoute: typeof TrackSleepRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/track/vaccines': {
      id: '/track/vaccines'
      path: '/track/vaccines'
      fullPath: '/track/vaccines'
      preLoaderRoute: typeof TrackVaccinesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/track/weight': {
      id: '/track/weight'
      path: '/track/weight'
      fullPath: '/track/weight'
      preLoaderRoute: typeof TrackWeightRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  ProfileRoute: ProfileRoute,
  ReportsRoute: ReportsRoute,
  SettingsRoute: SettingsRoute,
  TimelineRoute: TimelineRoute,
  TrackAlbumRoute: TrackAlbumRoute,
  TrackBilirubinRoute: TrackBilirubinRoute,
  TrackDoctorRoute: TrackDoctorRoute,
  TrackMedicinesRoute: TrackMedicinesRoute,
  TrackMilestonesRoute: TrackMilestonesRoute,
  TrackMilkRoute: TrackMilkRoute,
  TrackPottyRoute: TrackPottyRoute,
  TrackSleepRoute: TrackSleepRoute,
  TrackVaccinesRoute: TrackVaccinesRoute,
  TrackWeightRoute: TrackWeightRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
